language: node_js
sudo: required
node_js: 10
env:
  - PATH=$HOME/purescript:$PATH
install:
  - npm install -g bower pulp purescript@0.14.0
  - npx bower install
script:
  - travis_wait npx pulp build
  - travis_wait make run-example
  - travis_wait npx pulp test

cache:
  directories:
    - output
